### ISSUE TITLE
Merge conflict in province-master.csv

### ISSUE THREAD

**Issue by atredennick** [CEIDatUGA/COVID-19-DATA#35]
There appears to be a merge conflict in the province-master.csv [file](https://github.com/CEIDatUGA/COVID-19-DATA/blob/master/china/China_casedata/dxy_data/province_master.csv). The HEAD notifier is on the second line.

**Comment by mvevans89** [comment]
thanks! I'm hoping this will be fixed by the autoupdate at 8 pm tonight, but it not I'll take a look at it

**Comment by atredennick** [comment]
Great! I also found a merge conflict in the prefecture CSV (somewhere around line 6000). Sounds like that will probably also be fixed by the autoupdate. Thank you!

**Comment by mvevans89** [comment]
I think this has been fixed now. Forgot to tag the issue in the commit, but waiting to see if the github action successfully goes through tonight. If so, then I will close this issue

**Comment by arw36** [comment]
Seems like github action worked? and I just need to manually fill in the other dates (April 8th - 11th?)

**Comment by mvevans89** [comment]
I just ran it manually to deal with merge issue. I think it was from a while ago which was why the github action had been failing, but I had searched the files for the HEAD text and couldn't find it before. I basically just ran your script and completely wrote over the master csv's to get everything back on track. Re: the automatic china scraping I'm going to make a new issue to track that
