### ISSUE TITLE
US wiki autoupdate failing.

### ISSUE THREAD

**Issue by allopole** [CEIDatUGA/COVID-19-DATA#44]
us-wiki autoupdate : Mon Apr 20 10:04:41 UTC 2020 failed to return well formed data.  

Check if wiki table structure has changed, update script, and run manually.

**Comment by lsalvador** [comment]
Table structure has changed having now total rows per month in the middle. I will fix code and run it manually.

**Comment by allopole** [comment]
Recommend setting up a watchlist on wikipedia to monitor page changes and optionally email you when a change occurs. You have to create an account with wikipedia to do this.

**Comment by mvevans89** [comment]
oh cool. I didn't know about that watchlist thing. I'll look into it

**Comment by lsalvador** [comment]
Code fixed and tables uploaded manually to github
