### ISSUE TITLE
autopull of Apple data 

### ISSUE THREAD

**Issue by arw36** [CEIDatUGA/COVID-19-DATA#55]
@mvevans89 Wondering potential for autopulling the apple mobility from the https://www.apple.com/covid19/mobility website? Seems the link for button clicking is: "https://covid19-static.cdn-apple.com/covid19-mobility-data/2007HotfixDev58/v2/en-us/applemobilitytrends-2020-05-12.csv", so could set up to pull for file name to include yesterdays date? 

I would save this in: 
global/global_apple_covid_mobility_reports per the pull request

**Comment by mvevans89** [comment]
That sounds pretty reasonable and easy to set up. I can get it running tomorrow. Will you want to save old versions or just replace it daily?

**Comment by arw36** [comment]
Thanks! You can replace the file as previous dates are retained.

**Comment by mvevans89** [comment]
Not sure if this will work as well as we want via an automatic update. The whole url seems to be changing (today's is `https://covid19-static.cdn-apple.com/covid19-mobility-data/2008HotfixDev27/v2/en-us/applemobilitytrends-2020-05-14.csv`) and there isn't a way to scrape the url from the source code that I can see
