### ISSUE TITLE
dxy pulls are broken as of May 29

### ISSUE THREAD

**Issue by arw36** [CEIDatUGA/COVID-19-DATA#57]
- [x] manually add html for May 29, 30, 31 
- [x] fix for June dates  
- [ ] fix data pull breaks

**Comment by mvevans89** [comment]
this was fixed a while back but I forgot to close the issue. It now has a seperate workflow where the data is downloaded in one github action, adn the tables are made in another one, to make sure we don't lose data. Dates were also changed to YYYY-MM-DD to solve the date problem
