### ISSUE TITLE
Negative Confirmed Case Counts in UScases_by_state_wikipedia

### ISSUE THREAD

**Issue by Shufan-uga** [CEIDatUGA/COVID-19-DATA#61]
I was going through the UScases_by_state_wikipedia data set. There are states with negative increases of confirmed cases on certain days. What does it mean to have a negative value? Are they errors?

**Comment by mvevans89** [comment]
This is probably a question for @rlrichards

**Comment by rlrichards** [comment]
This actually isn't my code. I may have touched it at some point though and can take a look sometime this week though. I believe @lsalvador was working on that prior to automation.

**Comment by lsalvador** [comment]
These data are web scrapped directly from the wiki page and it is not clear why there should be negative numbers in the column of new daily cases (e.g. Arkansas on Aug 15 has -400 new cases). It could be a correction of the number of new cases in the previous days, but it is weird to have such a high number). I am going to double check these values with other data sources.

**Comment by mvevans89** [comment]
oops, sorry Robbie. For some reason I thought you were the wikipedia contact person

**Comment by rlrichards** [comment]
No worries! I did the world wiki data. You can tell how organically this all grew!

**Comment by lsalvador** [comment]
I doubled check with the John Hopkins and MIDAS-network datasets on github and they all match with the wikipedia one. John Hopkins and MIDAS present the cumulative values per day, while the wiki presents the number of new daily cases. Something happened on August 15th (and the difference between the 15th and the 14th is exactly -400):

(from John Hopkins)
13 Aug: 51766
14 Aug: 52392
**15 Aug: 51992**
16 Aug: 52665
17 Aug: 53077
18 Aug: 53487
