### ISSUE TITLE
World fatalities

### ISSUE THREAD

**Issue by jdrakephd** [CEIDatUGA/COVID-19-DATA#8]
I don't see where the "cumulative fatalities reported by country" in the old timeline spreadsheet (https://docs.google.com/spreadsheets/d/1SC28cM52m6s1gTJutpvFxadT9GGu-li90tsqkGuaM48/edit#gid=219891324) got ported over to the github -- am I missing it?

Related, did the "key events" tab can ported over. 

Fine for some of this to stay in the spreadsheet, but it needs to be clear what is the definitive source

**Comment by mvevans89** [comment]
Assuming this issue has been fixed since the world fatality data has been getting updated
